name: Start Cotiza (Render)
on:
  schedule:
    - cron: "30 13 * * 1-5"   # 10:30 ART (UTC=13:30)
  workflow_dispatch: {}

jobs:
  start:
    runs-on: ubuntu-latest
    steps:
      - run: curl -fsS https://cotiza-api-q3v6.onrender.com//cotizaciones/health || true
      - run: curl -fsS -X POST https://cotiza-api-q3v6.onrender.com/m/cotizaciones/iniciar_auto
